// <auto-generated />
using Liquors.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Liquors.Migrations
{
    [DbContext(typeof(LiquorsContext))]
    [Migration("20171130173927_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Liquors.Model.Alcohol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Alcohols");
                });

            modelBuilder.Entity("Liquors.Model.AlcoholVintage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlcoholId");

                    b.Property<int>("VintageId");

                    b.HasKey("Id");

                    b.HasIndex("AlcoholId");

                    b.HasIndex("VintageId");

                    b.ToTable("AlcoholVintage");
                });

            modelBuilder.Entity("Liquors.Model.Vintage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Vintages");
                });

            modelBuilder.Entity("Liquors.Model.Wine", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Country");

                    b.Property<string>("Region");

                    b.Property<string>("Type");

                    b.Property<string>("Winery");

                    b.HasKey("Id");

                    b.ToTable("Wine");
                });

            modelBuilder.Entity("Liquors.Model.AlcoholVintage", b =>
                {
                    b.HasOne("Liquors.Model.Alcohol", "Alcohol")
                        .WithMany("AlcoholVintage")
                        .HasForeignKey("AlcoholId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Liquors.Model.Vintage", "Vintage")
                        .WithMany("AlcoholVintage")
                        .HasForeignKey("VintageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Liquors.Model.Wine", b =>
                {
                    b.HasOne("Liquors.Model.Alcohol", "Alcohol")
                        .WithOne("Wine")
                        .HasForeignKey("Liquors.Model.Wine", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
